### ISSUE TITLE
refactor tests to use `fetch` instead of `request`

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1016]
As part of the https://github.com/ProjectEvergreen/greenwood/pull/1014, I realized that we although we have been using **request** to run HTTP calls in our tests, now with native `fetch`, we should use that instead.  That, and also, [**request**](https://www.npmjs.com/package/request) is deprecated.  😅 

So for example, in a few specs we do something like this when testing a server based command
```js
describe('Serve command with API specific behaviors for a JSON API', function() {
  let response = {};

  before(async function() {
    return new Promise((resolve, reject) => {
      request.get(`${hostname}/api/greeting?name=${name}`, (err, res, body) => {
        if (err) {
          reject();
        }

        response.body = JSON.parse(body);

        resolve();
      });
    });
  });

  ...
})
```

Instead, we should now be able to do this
```js
describe('Serve command with API specific behaviors for a JSON API', function() {
  const name = 'Greenwood';
  let response = {};
  let data = {};
  
  before(async function() {
    response = await fetch(`${hostname}/api/greeting?name=${name}`);
    data = await response.json();
  });
  
  ...
})
```

**Comment by DevLab2425** [comment]
@thescientist13 

I gave this one a shot, but getting some failures when running the tests on `master`.

Steps to reproduce:

1. Clone / pull latest from `master`
1. `yarn install --force` to ensure all deps are installed
1. `yarn test`...

The coverage report is created, but the tests fail along with the overall process. Am I missing something?

```
2587 passing (4m)
27 pending
31 failing
...
error Command failed with exit code 31.
```

**Comment by thescientist13** [comment]
@DevLab2425 
So this is just on master without making any changes to the code?  That's odd, I just ran them now myself and all seems fine?
```sh
  2677 passing (3m)
  27 pending
```

> yarn install --force to ensure all deps are installed

Does this change the lockfile at all?  I wonder what version of Yarn you are using?  just `yarn install` in theory should be enough.  (I'm still on 1.x)

One thought is for one of the failing test cases, find it's corresponding _*.spec.js_ file and
1. Change to `describe.only` at the top
1. Pass `true` to [`runner = new Runner()`](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/test/cases/build.config.default/build.config.default.spec.js#L33) to enable logging output

Be curious to see what errors you are getting.

**Comment by DevLab2425** [comment]
@thescientist13 
I was able to track it down using the `true` parameter. It looks like I had a process hanging on port 8080 and it was causing the runner to fail with an "in use" error. 🤦 

Killed that process and things are running fine. Not sure how I missed that otherwise. Sorry for the false alarm.

**Comment by thescientist13** [comment]
All good!  I'd be lying if I said I hadn't done that myself 😇
