### ISSUE TITLE
GraphQL plugin data `<script>` tag is being inserted before the opening `<head>` tag

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1053]
## Type of Change
Bug

## Summary
When using the GraphQL plugin, the `<script>` tag placeholder for serialized data is getting inserted _before_ the opening `<head>` tag, instead of after.
```html
  <script data-state="apollo" >
    window.__APOLLO_STATE__ = true;
  </script>
<head>
```

## Details
This one looks pretty obvious by [looking at the code](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/plugin-graphql/src/index.js#L67) 🤦‍♂️ 
```js
body = body.replace('<head>', `
  <script data-state="apollo" data-gwd-opt="none">
    window.__APOLLO_STATE__ = true;
  </script>
  <head>
`);
```

The `<head>` tag should be first in the `replace` string.

**Comment by Yasir761** [comment]
Is anyone working on this issue, if not I would like to work on this.

**Comment by thescientist13** [comment]
Hey @Yasir761 , no one as active on this issue yet, so feel free to give it a shot.  Let me know if you have any questions!

**Comment by Yasir761** [comment]
Thank you, surely I'll get in touch in when there is need.

**Comment by thescientist13** [comment]
There is also a link to our Slack group on the [project website header](https://www.greenwoodjs.io/) if you would like to join the team there. 👍

**Comment by Yasir761** [comment]
@thescientist13, I made a pull request, please have a look at it, if there are changes to be made, please let me know.
Thank You

**Comment by thescientist13** [comment]
Thanks!  Will check it out soon.
