### ISSUE TITLE
update logo for Web Components at the bottom of the website home page

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1057]
## Type of Change
website

## Summary
At the bottom of the home page is a logo for Web Components in the left tile.
https://www.greenwoodjs.io/
<img width="612" alt="Screen Shot 2023-02-06 at 9 31 42 PM" src="https://user-images.githubusercontent.com/895923/217132872-e1df9ed9-6794-4967-bd2d-68924d621188.png">

## Details
In the WebComponents Working Group, pGoogle / the Web Components SF group](https://github.com/w3c/webcomponents-cg/issues/4#issuecomment-1150073722) have offered up a new logo that the community has started gaining consensus on, so thought it would be good to get it updated on our website

![Logo1](https://user-images.githubusercontent.com/32065/172653241-3f423ae1-4ff0-4b95-ad74-554c1f04bf2c.png)
![Logo2](https://user-images.githubusercontent.com/32065/172655205-7452c730-6e06-454e-bbc1-f3f9bfa0b964.png)

**Comment by loki1205** [comment]
Hi, I would love to work with you on this. Can you please assign this task to me?

**Comment by thescientist13** [comment]
Thanks @loki1205 and will do!

Thinking about it, given the white background of the current home page, thinking that the white background variant version would work best.  Let me know if you have any questions!

**Comment by loki1205** [comment]
https://user-images.githubusercontent.com/32065/172653241-3f423ae1-4ff0-4b95-ad74-554c1f04bf2c.png

Hi, thanks for assigning. I am adding the image with white background. I have attached the link to the image that I am going to change the current logo to.

**Comment by loki1205** [comment]
Hi, I am sorry! Can you please tell me how I can create the exact output of the given website? I have changed the image just wanted to make sure it is changed before sending a pull request. Thank you!

**Comment by thescientist13** [comment]
Yeah, you can find the onboarding details in our [Contributing docs](https://github.com/ProjectEvergreen/greenwood/blob/master/.github/CONTRIBUTING.md) but basically the steps to follow are:
1. Have Node installed (16.x) or ideally, use NVM with `nvm use`
1. Have Yarn installed
1. Clone the repo
1. Run `yarn install`
1. Run `yarn develop`

All the docs and assets for the website are in the _www/_ directory.  Let me know if that helps!

**Comment by loki1205** [comment]
Hi, thanks for replying. I have created a PR kindly look into it and let me know if there are any changes. This is my first time contributing to open source and that's why I do not know how to do this correctly. If there are any mistakes kindly let me know I will be more than happy to help! And thanks for inviting me to join the Slack community, I will join immediately. Thanks again!

**Comment by thescientist13** [comment]
You're doing great so far!  Thanks for offering to help 😃

**Comment by loki1205** [comment]
Thank you! Please check the latest PR and let me know if there's something to change, I will be happy to help!

**Comment by thescientist13** [comment]
Thanks!  Found another good first issue if you are interested - https://github.com/ProjectEvergreen/greenwood/issues/1060

And if there's anything in particular you're looking to learn about web dev, NodeJS, etc feel free to let me know in the chat and I can see if there are some good tasks in the project that could align with that learning path for you.
