### ISSUE TITLE
remove extra component file from website

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1060]
## Type of Change
Other

## Summary
Looks like a file was left over from testing a feature but I think it can be removed.
https://github.com/ProjectEvergreen/greenwood/blob/master/www/components/card/card.native.js

## Details
Should just be able to delete it.

**Comment by loki1205** [comment]
Kindly assign it to me. I am interested.

**Comment by thescientist13** [comment]
Done!
