### ISSUE TITLE
broken link to documentation on default markdown configuration

### ISSUE THREAD

**Issue by lschierer** [ProjectEvergreen/greenwood#1293]
## Type of Change
Bug

## Summary / Details 
[The Markdown Section](https://www.greenwoodjs.io/docs/configuration/#markdown) has a broken link to a github page documenting the current default options for the unifiedjs configuration.  It isn't obvious what page should replace it or I would submit a pull request.

**Comment by thescientist13** [comment]
Wow, that links goes pretty far back in our project's history!  😅 

The updated location would be here
https://github.com/ProjectEvergreen/greenwood/blob/release/0.30.0/packages/cli/src/plugins/resource/plugin-standard-html.js#L74

**Comment by thescientist13** [comment]
Probably not a big deal for now since this section got touched up a bit for the new website, which should be launching by the end of the week, so will close this out then once its all live.
