### ISSUE TITLE
walk package error if @spectrum-web-components/action-menu is installed even if not used

### ISSUE THREAD

**Issue by lschierer** [ProjectEvergreen/greenwood#1309]
## Type of Change

 Bug 

## Summary

even if not used, if @spectrum-web-components/action-menu is installed as a dependency, you will get the following error when first loading a page:

```
-------------------------------------------------------
Welcome to Greenwood (v0.30.1) ♻️
-------------------------------------------------------
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
building from local sources...
Running Greenwood with the develop command.
Started local development server at http://localhost:1984
Now watching workspace directory (./src) for changes...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at Object.join (node:path:1250:7)
    at walkPackageJson (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lib/walker-package-ranger.js:176:65)
    at async walkPackageJson (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lib/walker-package-ranger.js:200:9)
    at async walkPackageJson (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lib/walker-package-ranger.js:200:9)
    at async walkPackageJson (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lib/walker-package-ranger.js:200:9)
    at async walkPackageJson (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lib/walker-package-ranger.js:200:9)
    at async NodeModulesResource.intercept (file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:96:9)
    at async file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lifecycles/serve.js:140:27
    at async file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lifecycles/serve.js:138:38
    at async file:///Users/lschiere/src/schierer/greenwood-repoductions/node_modules/@greenwood/cli/src/lifecycles/serve.js:138:38 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## Details

1. check out https://github.com/lschierer/greenwood-repoductions/tree/walkPackage
2. npm i
3. npm run dev
4. open a browser to http://localhost:1984

observe error in terminal

**Comment by lschierer** [comment]
I was able to use some of the other spectrum-web-components packages successfully, unsure what is different about this one.   
```
    "@spectrum-web-components/shared": "^1.0.1",
    "@spectrum-web-components/styles": "^1.0.1",
    "@spectrum-web-components/theme": "^1.0.1",
    "@spectrum-web-components/top-nav": "^1.0.1",
```

**Comment by lschierer** [comment]
I'm happy to submit a bug to the Spectrum guys, but the error message from Greenwood doesn't really give me enough detail to know what to submit.  I imagine the package is malformed in someway, but I'm not sure what it expects to be a string that its getting an object for instead.

**Comment by thescientist13** [comment]
Thanks for this report, though my initial hunch is that this one might be on Greenwood as I ran into something similar when playing around with [Shoelace](https://github.com/thescientist13/greenwood-lit-ssr/pull/18).  My plan there, and for this and in general, is to better flesh out our support for [_package.json_ exports field](https://nodejs.org/api/packages.html#package-entry-points).

This kind of work is definitely at the top of our priority queue so give me a little time and then hopefully we can unlock even more support for a much wider set of ecosystem packages.

**Comment by lschierer** [comment]
cool, well if you need more information, I can try to gather it.

**Comment by thescientist13** [comment]
thank you!  will keep posted on progress here and let you know.

**Comment by thescientist13** [comment]
Hey @lschierer 

Just wanted to give you an update that I've been steadily working on a refactor of the import map generation code as a general umbrella to address and improve upon some of the related issues you've raised, and just wanted to share that I now how have Spectrum WCs working.  🎉 

https://github.com/user-attachments/assets/8f41c30e-0bce-4bf4-8eba-ef5da2bc51e2

Give me another couple week or so and I should have all this work submitted as a PR and then will be able to cut a new Greenwood release candidate release that we can start testing in your project.  This work should also encompass #1310 and better handle #1313 .

**Comment by lschierer** [comment]
That's awesome to hear!  the forward progress that Greenwood is making is great to see :-)
