### ISSUE TITLE
[RFC] Route Based Code Splitting

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#136]
## Type of Change
- [x] New Feature Request (RFC)
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
As it stands now it looks like Greenwood only creates on _index.js_.  Would like to look into how we can possibly do route based code splitting, or I guess in the context of this project, template based code splitting?
<img width="1642" alt="Screen Shot 2019-09-18 at 7 59 54 AM" src="https://user-images.githubusercontent.com/895923/65146697-6e713b80-d9ea-11e9-9d00-915c42d6616f.png">

## Details
In particular this is a potential concern until larger projects can be tested because if ALL the content / code ends up in _index.js_ then it will absolutely crush larger projects even though currently the Greenwood website scores well.  

Ideally we should be able to configure this all through webpack.
https://webpack.js.org/plugins/split-chunks-plugin/

We should also want to handle / consider splitting out vendor code into it's own chunk too.

**Comment by hutchgrant** [comment]
lit-redux-router allows for lazy loading components, I know because I wrote that functionality into it(only time I've been able to say that). With webpack, we can use [dynamic imports](chunkFilename: '[name].bundle.js')

*app.js*
```js
import { navigate } from 'lit-redux-router';
import store from './store.js';

class MyApp extends LitElement {
  render() {
    return html`
      <div class="app-content">
        <lit-route
          path="/docs"
          component="my-docs"
          .resolve="${() => import('./docs.js')}"
          loading="my-loading"
        ></lit-route>
      </div>
    `;
  }
}
customElements.define('my-app', MyApp);

class MyLoading extends LitElement {
  render() {
    return html`
      <style>
        h1 {
          margin-top: 0;
          margin-bottom: 16px;
        }
      </style>
      <h1>Loading...</h1>
    `;
  }
}
```
This will display a loading component, while we wait for the new page component to resolve. 

*webpack.config.common.js*
```js
    output: {
      filename: '[name].bundle.js',
      chunkFilename: '[name].bundle.js',
      publicPath: 'dist/',
      path: path.resolve(__dirname, 'dist'),
    },
```

This will split our bundle into chunks. 

In order to use that, we would have to adjust the scaffold to dynamically import each page component in addition to webpack.

**Comment by thescientist13** [comment]
Yeah, was thinking something like that as well.  Will be really exciting to implement this to coincide with data in / data out combo.  🙌
