### ISSUE TITLE
[RFC] User Extensibility - Lifecycles and Plugins

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#17]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Allowing users to extend functionality of the tool will be the best way to gain adoption and support.  Things like lifecycles and plugins can provide consistent APIs and hooks for users to tap into the Greenwood build process and extend the functionality to support their project's needs.

## Details
Some of these may be maintained by Greenwood itself, but would want to flesh out
- ~~Lifecycles: How and when are operations run (phases), and what's the inputs and outputs for each phase~~
- Plugins: Extend the build phase by providing your own **webpack** plugins?

Full details mapped out here
https://github.com/ProjectEvergreen/greenwood/issues/17#issuecomment-523706157

**Comment by thescientist13** [comment]
Watched this video and they used rollup instead of **webpack**, but it definitely highlighted a little bit of a more simple way to write plugins.
https://www.youtube.com/watch?v=TsTt7Tja30Q

Or we could just people pass in webpack plugins?

**Comment by thescientist13** [comment]
So had an idea for plugins, that they can be used (at least for one case) to inject HTML into _index.html_.  A couple use cases being:
- Google Analytics
- [Poylfills](#9)

**Comment by thescientist13** [comment]
## Overview
What I'm thinking is that plugins will be the top level "primitive" with a few different types and APIs: 
- `hook` - Prefined places in _index.html_ that you can be used to inject custom HTML, like with [`spaIndexFallback`](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/config/webpack.config.develop.js#L70).  Anticipated hooks:
  - `analytics` - Google Analytics, Snowplow.  Will make an issue for creating one for Greenwood.
  - `meta` - Useful for adding static build time `<meta>`, `<title>`, favicons, etc
  -  `polyfills`- Good for supporting what Greenwood will provide as a plugin for polyfills
 - For more complex use cases, user can just as easily [override _index.html_ themselves](https://github.com/thegreenhouseio/www.thegreenhouse.io/blob/2.0.0/src/templates/index.html).
- `build` - Alter the build directly by passing in webpack plugins directly! (YMMV).  Will have options for `common`, `develop`, `prod` depending on where the plugin should get used
- `source` - Tapping into the graph, see #115 / #21 like when consuming from external sources like a headless CMS
- `lifecycls` - TBD and should be defined in another issue.
- `transform` - Different input types like _.yaml_, html, or JavaScript instead of just markdown, like in #170.  Will need it's own issue

Plugins would get access to a read only version of the Greenwood `compilation` object that would provide plugins information like contexts (inpout / output directories and paths), configuration (e.g. _greenwood.config.js_), and the overall build state.  Plugins would be instantiated in _greenwood.config.js_ as an Array called `plugins`.

_example:_
```javascript
module.exports = {
  title: 'My Project',

  ...

  plugins: [{
    type: 'hook|webpack|data|lifecycle|transform',  // @string required, no default
    provider: (compilation) => { /* do stuff here */ } // @function required (@return depends on type), no default
  }]
}
```

A plugin can define multiple types depending on what the task at hand. An example of a plugin having multiple types is that of a Polyfill plugin that installs dependencies locally via npm.  In that case not only would we need a hook for tapping into the `analytics` hook, but would also need to be able to [includes those polyfills from _node_modules_](https://github.com/ProjectEvergreen/greenwood/issues/178) as part of the Greenwood build using something like `CopyWebpackPlugin` so that the files will be available in _public/_ to match the path set in the `hook` in _index.html_.

Greenwood should try and encourage development / contributions to the monorepo itself, a la Gatsby
https://github.com/gatsbyjs/gatsby/tree/master/packages


For the sake of this issue, I'll just cover `hook` and `build` plugin types but it should provide enough of a blue print for more follow up tasks.  (covered at the end)


## Hook
In particular _index.html_ provides the most oppourtunity right now as things like polyfills, analytics, and PWA features like _manifest.json_ and ServiceWorkers need to be installed in a global scope and /or unbundled.  These would essentially be pre-defined find / replace hooks in _index.html_.

### Usage
A great example use case is injecting Google Analytics into _index.html_. 

In Greenwood's _index.html_ we would add this marker
```html
  ...

  <%= htmlWebpackPlugin.options.hookGreenwoodAnalytics %>
```

Then in Greenwood config, you tap into it like this:
```javascript
module.exports = {
  title: 'My App'

  ...

  plugins: [{
    type: 'hook',
    provider: (compilation) => {
      // you can access things like config, context if you need from compilation
      return {
        hookGreenwoodAnalytics: `
          <!-- Google Analytics -->
          <script>
            window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
            ga('create', 'UA-XXXXXXX', 'auto');
            ga('send', 'pageview');
          </script>
          <script async src='https://www.google-analytics.com/analytics.js'></script>
          <!-- End Google Analytics -->
        `
      ]
    }
  }]
}
```

> The greenwood plugin would essentially just wrap all of this for a user and just ask for `analyticsId`.

It should be noted that if these specific hook types are too limiting (we should support a basic set of common hooks), users can just make their own _index.html_ and configure all of these Greenwood hooks themselves (if they wanted) or just create their own.


## Build
Basically you can pass a webpack plugin! Mileage may vary, but we could provide a list of know plugins that work in this way.  (like ones that we use in our plugins)


### Usage
For a consumer, usage would look something like this in _greenwood.config.js_ where the `provider` function in this case returns an instance of a webpack plugin.

_example:_
```javascript
const { version } = require('package.json');
const webpack = require('webpack');

module.exports = {
  title: 'My App'
  
  ...
  
  plugins: [{
    type: 'build'
    provider: (compilation) => {
      const { config } = compilation;
      
      return new webpack.BannerPlugin({
        banner: `${config.title} v${version}: built on ${new Date().getTime()}`
      });
    }
  ]
}
```

## Action Items / Next Steps
1. Create mew issues:
    - RFC: Lifecycles
    - RFC: Transforms
    - Plugin: Google Analytics (will add to current project)
    - Plugin: Polyfills (will add to current project)
1. Create a release branch, to make a success of PRs and opened against master
1. Setup Lerna + Yarn workspaces
1. Create Google Analytics Plugin
1. Create Polyfills Plugin
1. [Install Polyfills from npm](https://github.com/ProjectEvergreen/greenwood/issues/178)
1. [Differential Loading](https://github.com/ProjectEvergreen/greenwood/issues/9)
1. Alpha testing
1. Merge to master + release
1. Further considerations
    - more hooks: manifest, meta, title, favicon hooks
    - PWA plugin: manifest, favicon, service workers, etc

**Comment by hutchgrant** [comment]
Those examples are only related to index.html, I'm concerned with build time hooks related to components, templates, content.  I was thinking more of a base class, or series of base classes which contain all the functions needed for specific types of plugins.  We would create a lifecycle that specifically loops through all the installed plugins, creates a new object from each plugin class, each of which extends and utilizes a library of plugin functions. The implementation of that is my issue, because each plugin will require unique configurations, and certain plugins as you pointed out need to be implemented at different times and places.  While I do want webpack plugins accessible to the default webpack configuration, I'm thinking about different forms of accessibility like hooks within templates(not just index.html files) that require pre-build caching etc (e.g. Meta plugin, headless CMS).

**Comment by thescientist13** [comment]
Hmm... From your PR it seems like we are more or less on the same page but your comment would make it seem like we are not, so that still has me scratching my head a little bit.   Let me cover some of your points and see if that helps further align us.

> I'm thinking about different forms of extensibility like hooks within templates(not just index.html files)

I did lead with _five_ examples of this in the opening of my comment.  (I've since numbered them so hopefully this makes things a bit clearer?).  

Hooks and direct webpack plugins are but 2 of these 5.  The rest are all better covered in RFC issues which I linked out to.

> I'm concerned with build time hooks related to components, templates, content

Like I said, i've listed all the examples I can think of including content.  I want to avoid "components"  in the build / CLI though because that should probably be left to userland / runtime code responsibilities.  This is what we've been talking about already in the [Build Time Data Injection RFC](https://github.com/ProjectEvergreen/greenwood/issues/115) so that's where I would like to see that go, generally.

Perhaps you could be more specific though in identifying what the role of these use cases would be and how they differentiate from what I've provided so that I can better understand what gaps you are seeing?

> Those examples are only related to index.html, 

Correct, and that was intentional.  I did say this after all...

_"For the sake of this issue, I'll just cover hook and build plugin types **but it should provide enough of a blue print for more follow up tasks. (covered at the end)**"


>  I was thinking more of a base class, or series of base classes which contain all the functions needed for specific types of plugins.

Yeah, a base class is another way to establish the contract plugins so that does raise a good point and might be a good way to establish some consistency.

Though some compelling advantages towards functions are that they are first class citizens in JavaScript, are super easy to pass around, don't have to worry about `new`, and are going to be a lot more performant (I would imagine) then spinning up a bunch of classes that just get used and tossed away.
  
----

I encourage you to go back over and read through my comments again as I think it covers a broad set of use cases pulling from existing RFCs we've discussed and aims to pull them under one common API (plugins), of which there will be a few different options within that.

I just happen to be starting with the hook / webpack options because:
- they are smaller chunks to bite off right now
- have pretty clearly defined use cases already
- given their "smallness" make for a good first step into setting up our monorepo

I think we are more or less in line so I just want to make sure I'm not missing any use cases but I would like to start following my action items at least and making / tracking all the relevant work.
