### ISSUE TITLE
hook plugins not working when using greenwood develop

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#210]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Observed when working on #208 that hook plugins don't seem to be showing up when running `greenwood develop` because `getOutboundLink` was undefined.
<img width="1638" alt="Screen Shot 2019-09-24 at 8 47 34 PM" src="https://user-images.githubusercontent.com/895923/65560518-043a2880-df0d-11e9-8c15-69ec65ecd907.png">

## Details
Comparing the output, it's clear these custom hooks are not getting included.  However our custom fallback handling script is there.  🤔 

#### develop
<img width="1636" alt="Screen Shot 2019-09-24 at 8 52 07 PM" src="https://user-images.githubusercontent.com/895923/65560576-45323d00-df0d-11e9-87c2-c813c45e4425.png">

#### build
<img width="1642" alt="Screen Shot 2019-09-24 at 8 53 28 PM" src="https://user-images.githubusercontent.com/895923/65560607-6135de80-df0d-11e9-918e-1c339c563f44.png">

**Comment by hutchgrant** [comment]
I observed this on `master` branch but not in `technical/issue-176-404-not-building` with the removal of the fallback script, it works as expected with getOutboundLink in develop.

**Comment by hutchgrant** [comment]
![develop_210](https://user-images.githubusercontent.com/1429612/67344684-acd8a980-f506-11e9-897c-df0e88fb0bfb.png)

branch: technical/issue-176-404-not-building

**Comment by thescientist13** [comment]
Did some quick testing, and I think the issue might be that the configuration in [_webpack.config.develop.js_](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/config/webpack.config.develop.js#L68) is overwriting the contents created initially by [_webpack.config.common.js_](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/config/webpack.config.common.js#L128), and so not actually doing a merge per se.  

In [_webpack.config.prod.js_](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/config/webpack.config.prod.js#L18), the only thing happening there is the not found page handling and so would explain why there is no issue in prod.

Which would explain why removing those `HtmlWebpackPlugin` configurations made it work then.

So maybe just our implementation of how we're using it is a little off then, so this issue can provide a good opportunity to clean that up a little so everything plays together nicely and as expected.  Will keep poking around.
