### ISSUE TITLE
Inconsistent use of quotes on meta attributes

### ISSUE THREAD

**Issue by DevLab2425** [ProjectEvergreen/greenwood#218]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

The `<meta />` tags contained within the `index.html` use single quotes, where other tags within the template use double quotes. Industries
## Details

~~https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/templates/index.html#L6-L10~~
Updated path:
https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/templates/index.html

**Comment by thescientist13** [comment]
Good 👀 @DevLab2425 !

Yeah, I would be up for having that be consistent.  Feel free to submit a PR if you're up for it!  👍
