### ISSUE TITLE
website pages with a shelf component are showing console errors when there are no subitems

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#222]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Several bugs related to the items[] array within our shelf if no items present.  Solution is to make sure array is initialized and to use a map.  These errors are viewable at https://www.greenwoodjs.io/getting-started/

## Details
<img width="600" alt="shelf-console-error" src="https://user-images.githubusercontent.com/895923/66876296-4809d600-ef7f-11e9-89d4-98822c9339ec.png">

```
Uncaught TypeError: Cannot read property 'length' of undefined
Uncaught TypeError: Cannot read property 'map' of undefined
Uncaught TypeError: Cannot read property 'findIndex' of undefined
```

**Comment by thescientist13** [comment]
Thanks for reporting @hutchgrant , added a couple details of my own.
