### ISSUE TITLE
stop lerna from publishing with a prefix

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#226]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Lerna is automatically publishing tags with a prefix of `v`.  I would prefer this not happen.

## Details
https://github.com/ProjectEvergreen/greenwood

**Comment by thescientist13** [comment]
Well, babel seems to use the `v` prefix.
https://github.com/babel/babel

Also, GitHub seems to recommend it.
https://github.com/ProjectEvergreen/greenwood/releases/new
<img width="304" alt="Screen Shot 2019-10-15 at 11 02 37 PM" src="https://user-images.githubusercontent.com/895923/66884710-09d0de80-efa0-11e9-90e3-6dc315453719.png">

**Comment by thescientist13** [comment]
Welp, seems like the `v` is a best practice?
https://stackoverflow.com/questions/21639437/git-flow-release-branches-and-tags-with-or-without-v-prefix

TIL

**Comment by thescientist13** [comment]
Welp, according to semver, it's required
https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags
> When tagging releases in a version control system, **the tag for a version MUST be "vX.Y.Z" e.g. "v3.1.0".**

**Comment by hutchgrant** [comment]
So shall we close this one?

**Comment by thescientist13** [comment]
we shall 😄
