### ISSUE TITLE
test out webpack 5 beta

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#227]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
https://twitter.com/thelarkinn/status/1183828023771942913

## Details
Let's give it a shot!  The removal of polyfills runtime seems like it could be a nice boost to overall bundle sizes.

**Comment by hutchgrant** [comment]
```
Error: Cannot find module 'copy-webpack-plugin'
```

No dice.

**Comment by thescientist13** [comment]
New beta
https://twitter.com/thelarkinn/status/1194350535836454912

**Comment by thescientist13** [comment]
As part of #355 / #417 webpack wont be used in the project anymore, so this issue will become invalid once this gets merged and release.

**Comment by thescientist13** [comment]
v0.10.0 released, webpack related issues no longer apply to the project
