### ISSUE TITLE
provide a local Dockerfile of the continuous integration environment

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#229]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
As we found as part of #213 , having a local version of the Docker container of what CircleCI is running was really helpful.  Along with #21 , being able to test CMSs will also be useful, so getting a basic implementation to work off will be a good start.

## Details
This is what I have so far, but need to make it mount the local workspace directly to provide a 1:1 mapping
```shell
# Build: docker build -t nodejs-dev .
# Connect: docker run --name nodejs-greenwood -i -t nodejs-dev
# Run: yarn build, yarn test, etc
# Disconnect: exit
# Destroy: docker rm nodejs-greenwood

# TODO mount / mirror workspace, not just COPY

FROM thegreenhouse/nodejs-dev:0.4.0

# Set the working directory to /app
WORKDIR /workspace

# Copy the current directory contents into the container at /app
COPY . /workspace

# TODO
RUN yarn install
```

**Comment by hutchgrant** [comment]
I built the same image as we have on circleci. If we can trim this image down, that would be great.

Save as Dockerfile

```bash
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl vim git bzip2 ssh build-essential

# install HeadlessChrome X11 packages
# https://github.com/Quramy/puppeteer-example#with-docker-based-ci-services
RUN apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
      libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
      libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
      libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
      ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

# install Chrome and Java JRE
# https://askubuntu.com/questions/510056/how-to-install-google-chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add 
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update && apt-get install -y google-chrome-stable default-jre

# install NodeJS LTS
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

# install latest yarn@1.0.0 and upgrade to latest release of npm@5.0.0
# use yarn to install npm \_(ツ)_/¯
# https://stackoverflow.com/questions/44269086/how-to-upgrade-npm-to-npm5-on-the-latest-node-docker-image
RUN npm install -g yarn@^1.10.0 && yarn global add npm@^6.0.0
```
Built container image with:

```bash
docker build -t nodejs-dev .
```


Then I ran it with a mounted a directory using binding. It's not ideal because it's causing a permission nightmare. 

```bash
docker run -it --name devtest --mount type=bind,source=/home/skynet/workspace/evergreen/greenwood,target=/workspace/greenwood nodejs-dev
```

**Comment by thescientist13** [comment]
> I built the same image as we have on circleci. _If we can trim this image down_, that would be great.

what you have is the same as CircleCI, which is using `FROM thegreenhouse/nodejs-dev:0.4.0`.  Maybe I'm missing something but wouldn't want to use that instead off a copy / paste?

**Comment by hutchgrant** [comment]
Well instead of pull that image, you can custom build your own is the point. So I'm taking the dockerfile from that image and showing you what it contains so we can strip it if need be,

**Comment by thescientist13** [comment]
Sure, but the thing we wanted was the _same_ image as CI, right?  That's what helped us repro.

I agree, If someone wants to hack with it after the fact great, but we should probably just _commit_ the actual thing we want.  We can link to the "source" so if someone wants to tinker more locally, they can.

But if there is a new release of that image, then we just have to bump the version to keep things in lockstep.   

Plus, for providing a testing environment as part of #21 , we will likely be using `docker compose` so using images will be the eventual workflow anyway.
