### ISSUE TITLE
[RFC] Monorepo

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#24]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

[lerna](https://github.com/lerna/lerna) makes it easy to manage deployment and version control of multiple packages to the npm registry. Currently, there's a single package.json and it manages the overall project but we need a npm package.json for each individual package.  

## Details

We have the project almost setup for this with the packages folder structure, but we need to move the package.json to the cli package and run `npx lerna init` which will generate a new package.json and lerna.json file.

We also need to change paths of scripts within the package.json to be relative to the cli package folder, instead of what it is now in the root directory.

**Comment by thescientist13** [comment]
Couple good videos on monorepos I stumbled across
- https://www.youtube.com/watch?v=pU87ufl2lDc
- https://www.youtube.com/watch?v=8uigR84I4M4
