### ISSUE TITLE
articulate Greenwood's vision / value through the home page

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#268]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
In light of the work being done around [build time data injection and external data sources](https://github.com/ProjectEvergreen/greenwood/projects/4), and in evaluating other similar projects like [eleventy](https://www.11ty.dev/), it will become important for Greenwood to make sure it can establish and communicate it's uniqueness (or so we believe) to the community.  The goal of this issue is to discuss updates to the home page to account for different takes / copy / etc to communicate that vision.

> This will be important as for post MVP and for pro bono / outreach work, it will be critical that the website can do the talking for us.  (This will be aided by additional DX specific work in [the **Project 5 - MVP Ready**](https://github.com/ProjectEvergreen/greenwood/projects/5))

## Details
The biggest vision goal of Greenwood is to provide a modern experience for generating static sites, namely JavaScript as a first class citizen.  Just like developing Gatsby is just like developing React, so should Greenwood for Web Components.  Instead of templating languages like [eleventy]() and other SSGs, promote usage of JavaScript with things like `map` and `filter`, all done at build time.

Proposed changes to the home page
1. Logos - GraphQL, Web Components, Puppeteer / Webpack* (something that communicates modern webapp development ultimately)
    - lighthouse, to represent performance?
1. Awareness of JAM Stack, a la #175 
1. Better heading byline?  _develop like a webapp, deploy like a static site_

**Comment by aholtzman** [comment]
Thoughts for basic layout of the landing page...

Above the fold - Headline...
"Write Javascript"
"Compile performance"
"Greenwood the static size generator for Web Components"

Below the fold - One page marketing Slick...
Top Section - bullet points of what is possible with greenwood, dev focused
Bottom section - highlight was is happening under the hood (IE "Leveraging the power of WebPack & GraphQL...")

I can play with some design concepts once we have a bit of material & copy to work with.

**Comment by thescientist13** [comment]
Pretty good article by Gatsby on how they articulate how Gatsby works
https://www.gatsbyjs.org/blog/2020-01-30-why-gatsby-is-better-with-javascript/

**Comment by thescientist13** [comment]
This good [article on Gatsby](https://joshwcomeau.com/gatsby/a-static-future/) may be relevant?  Especially since there's nothing "static" about what you have to build with Greenwood, per se.

**Comment by thescientist13** [comment]
"escalating" this as now that we have defined #418 and started development on #436, this will need to change, as certainly webpack from the home page isn't relevant anymore.  But more to the point, the vision / philosophy of the project changed starting with #355 and that comes with some technology shifts.  Should make sure this now covers:
- Home Page
- About Page
