### ISSUE TITLE
query data sorting and filtering

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#288]
## Type of Change
- [x] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Coming out of discussions in meeting and #271 and #285 , it seems like the topic of sorting and filter in GraphQL (like for solving the issue of the shelf's sub nav) should be moved to its own issue.

## Details
There are a couple options under consideration for achieving this

### Queries
The enhancement here would be to allow users to request the order of results instead of having to do it themselves (somewhat negating the value of querying for the data in the first place).

##### Declarative
One option is to be able to do something like this 
```gql
query {
  navigation{
    label,
      'page-a',
      'page-c',
      'page-b'
    link
  }
}
```

##### Params
Another way would be to have it done through the client / GraphQL
```javascript
async connectedCallback() {
  super.connectedCallback();

  const response = await client.query({
    query: NavigationQuery,
    variables: {
      sort: [
         label: [
           'page-a',
           'page-d',
           'page-b'
         ]
      }
  });

  this.navigation = response.data.navigation;
}

```

#### Front Matter
The front matter approach would be similar to what is being requested in  #274 , in that menu configuration could be added as front matter, e.g.
```md
---
label: 'features'
menu: side
title: 'Features'
index: 2
```

And then queried.

But also like in #274, this would require everything to be 100% percent transparent.  In #285, one issue is that the specific logic to the user (e.g. `menu`) is too specific to the implementation of the Greenwood website, and not really useful or should be hardcoded into any public to users (e.g resolvers, queries, etc).

**Comment by hutchgrant** [comment]
> In #285, one issue is that the specific logic to the user (e.g. menu) is too specific to the implementation of the Greenwood website

I disagree, the logic for any menu, on any website, and could be utilized for footers, side menus, or navigation. The example from that PR is using greenwood website, but nothing in the logic is specific to greenwood website.

**Comment by thescientist13** [comment]
I think this may beyond our scope or that of GraphQL, but if anyone comes looking for this and has a need, please feel free to reopen.  😃
