### ISSUE TITLE
Page automatically scrolling to first h3 tag

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#309]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
[This link](https://www.greenwoodjs.io/docs/configuration/) will scroll the page down to the h3 element when it should not.  This behaviour is present on all pages. 

## Details

This likely has to do with the scroll component. When we refresh a page a `/` is appended to the end of the link which may be causing an issue with the logic.

**Comment by thescientist13** [comment]
Hmm, seems related to #331 .  Will link all these together and make sure we can find a way to fix this within Greenwood itself.
