### ISSUE TITLE
Create a guide for using CloudFlare workers (and AWS, Firebase) to host a Greenwood site

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#326]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
In the spirit of #313 and #320, should create a guide for [CloudFlare Workers](https://workers.cloudflare.com/), since @aholtzman  was so kind to offer.  :)

## Details
See title.  :)

**Comment by hutchgrant** [comment]
Also gcloud, s3, github(i think we have an issue for that one). Any static host deployment guides are appreciated.
