### ISSUE TITLE
[website] Scroll component only scrolls to h3 elements

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#329]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
With the addition of the MenuQuery in #295 we will have the ability to link any headings from a page e.g. h1, h2, h3 etc, into a single menu.  Currently, the scroll component is hardcoded to only scroll to h3 elements containing a hash. It would be ideal if we could scroll to any type of heading element.

## Details

scroll.js
```js
    // clean hash string, remove # and replace - with spaces
    hash = hash.replace('#', '').toLowerCase();
    // for cases of multiple hyphens
    hash = hash.replace(/-/g, ' ');
    // query text
    const heading = contains('h3', hash)[0];
```

**Comment by thescientist13** [comment]
Maybe we should publish this as an ([evergreen](https://github.com/hutchgrant/evergreen-web-components)) web component  once we get full heading support?  One thing that i love about GitHub is that you can link to headings in .md docs. 

ex. 
https://github.com/ProjectEvergreen/greenwood#documentation

That would be super awesome to have for Greenwood websites and so we should see how to move this out _www/_ once this enhancement is complete.
