### ISSUE TITLE
routes with and without trailing forward slash causes route "misses"

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#331]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
As evidenced in PR #308, it looks like if there is or isn't a forward slash at the end of a route. e.g. 

http://domain.com/about 

vs.

http://domain.com/about/

Can lead to issues with matching against active routes in GraphQL / coming out of the Greenwood graph and even cause errors in the console, although I think Netlify will add / forward to the `/` so then it "catches".

<img width="1647" alt="77268328-ea8b5b00-6c7b-11ea-8cff-a53442cc83f5" src="https://user-images.githubusercontent.com/895923/79667701-12d77e00-8184-11ea-9b19-f9823a18088c.png">

## Details
I think anywhere where we are matching against an active route or using `window.location.hostname` or similar to find out the current page, we will need to evaluate how it is being implemented and try and build a fairly robust / non fragile solution.

Also see #310 for reference.

**Comment by thescientist13** [comment]
Well, now adding the forward slash removes the `undefined` error, but adds this error now instead 😞 🤷 
<img width="1647" alt="Screen Shot 2020-04-22 at 6 28 41 PM" src="https://user-images.githubusercontent.com/895923/80040131-6c62e400-84c7-11ea-8e0f-604658bffec3.png">
```
index.b37c464fdfd3e49a05d7.bundle.js:1 Uncaught (in promise) Invariant Violation: Invariant Violation: 8 (see https://github.com/apollographql/invariant-packages)
    at new e (https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:1:16081)
    at https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:58147
    at Array.forEach (<anonymous>)
    at n.diffQueryAgainstStore (https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:58105)
    at n.readQueryFromStore (https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:57465)
    at e.read (https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:67395)
    at e.n.readQuery (https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:47470)
    at https://deploy-preview-284--elastic-blackwell-3aef44.netlify.app/index.b37c464fdfd3e49a05d7.bundle.js:117:73775
```

cc: @hutchgrant

**Comment by hutchgrant** [comment]
For our site, the solution on netlify is: 

> Settings > Build & deploy > Post processing > Asset optimization  then disable asset optimization and then disable pretty urls

Which eliminates the trailing slash.

The problem is that we're caching routes with the / and therefore when we visit pages with the / our cache does not contain a matching route which gives us these errors.

Quick solution is to remove trailing slash to begin with, its unnecessary.

**Comment by hutchgrant** [comment]
We could also eliminate trailing slash from index page routes as well. 

```
// determine if this is an index file, if so set route to '/'
let route = fileRoute === '/index' ? '' : fileRoute;
```

The issue with that is:

if you have a file `/docs/index.md` it would resolve to `/docs` while currently it resolves to `/docs/`.
if you have a file /docs.md it would also resolve to `/docs` in both cases

**Comment by thescientist13** [comment]
Good call @hutchgrant on Netlify settings .  

Applied this setting for now, seems to have fixed the issue.  💯 
<img width="1032" alt="Screen Shot 2020-04-24 at 1 58 36 PM" src="https://user-images.githubusercontent.com/895923/80242921-3000c680-8634-11ea-9d1a-d542dcb61661.png">

Let me add this issue to our Tuesday agenda to make sure there's nothing else we should be doing and / or documenting.

**Comment by thescientist13** [comment]
So the question is: What should our default link format be, with or without a forward slash; `/`, and that either way it should be configurable, most likely from _greenwood.config.js_.

**Comment by thescientist13** [comment]
From [this PR](https://github.com/ProjectEvergreen/greenwood/pull/344/files#r418359787), maybe anywhere we have to do some sort of matching, we should use a RegExp?  Then we could only have `/docs` and it should still match if a route is `/docs/`?  Then maybe no configuration?  But maybe it would still be good to configure the `/` somehow?  Not sure... 🤔

**Comment by thescientist13** [comment]
Hmm, now i'm getting the cache invariants locally using the serve command. 😞 
<img width="1660" alt="Screen Shot 2020-05-06 at 7 39 37 PM" src="https://user-images.githubusercontent.com/895923/81239268-56c6e180-8fd2-11ea-89eb-94f1b61e395b.png">

Maybe an issue with the local web server prettiying URLs.

**Comment by thescientist13** [comment]
It looks like `ws` is adding the forward slash... I wonder if that is happening when rendering, so all our cached calls to `window.location.pathname` will be forced to have the `/` too? 🤔

**Comment by thescientist13** [comment]
I've normalized all routes as ending with `/` as part of #449
