### ISSUE TITLE
website shelf menu gets stuck on a page where first nav item has sub headings

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#340]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
If you go to the guides page right now, you will find that while the content displayed is that of the _guides/index.md_ page, the shelf on the left is already auto-expanded to show the link heading children of the first shelf item.
<img width="1665" alt="Screen Shot 2020-04-29 at 9 00 54 AM" src="https://user-images.githubusercontent.com/895923/80599199-900eb880-89f8-11ea-8fb1-603e38c9c201.png">

However, clicking any of those links or the nav item itself does nothing.  The only way to access the content is to click the downward facing carrot, which is not very intuitive.

## Details
It is likely due to [this logic](https://github.com/ProjectEvergreen/greenwood/blob/master/www/components/shelf/shelf.js#L56), which auto expands the first selected item automatically, but I don't think it checks to see if it's on a top level / index.md route, e.g. _/guides/_ to know if it _should_ expand or not.

```js
  expandRoute(path) {
    // find list item containing current window.location.pathname
    let routeShelfListIndex = this.shelfList.findIndex(list => {
      return list.item.link.indexOf(path) >= 0;
    });

    if (routeShelfListIndex > -1) {
      this.shelfList[routeShelfListIndex].selected = true;
      this.selectedIndex = routeShelfListIndex;
      // force re-render
      this.requestUpdate();
    }
  }
```

This gets called during `onConnectedCallback` so will happen each time.  This isn't an issue for other pages because so far the guides page is the only page that has linkHeadings for it's first shelf child.

**Comment by thescientist13** [comment]
One thing I notice is that the shelf is always firing the `connectedCallback` event, even if clicking shelf items within a single top level page.  (e.g. just selecting the items from the left without changing the header navigation).

I wonder if this is related to the [multiple `fetch`](https://github.com/ProjectEvergreen/greenwood/issues/317#issuecomment-619227081) calls we're seeing?

**Comment by hutchgrant** [comment]
I have an explanation for why `connectedCallback` is called multiple times.

It has to do with the routing.

![dom](https://user-images.githubusercontent.com/1429612/80624636-f6580300-8a19-11ea-97e8-b75332a53aa7.png)

> connectedCallback: Invoked when a component is added to the document’s DOM.

[lit-element](https://lit-element.polymer-project.org/guide/lifecycle) docs

When I click the netlify route, the component is readded to the dom, which calls the connectedCallback again for the entire tree. 

```
page-template |-------- header
                        |-------- shelf
                        |-------- wc-md-component
                        |--------- footer
```

Entire thing is reloaded every single route change.

**Comment by hutchgrant** [comment]
Currently, we're set to query graphql on connectedCallback and instead it should be conditionally, in our case we really only need to fetch a new menu when the main category changes(docs -> getting-started, etc). We're also not managing the state correctly here as the query data is lost each time a route changes.

**Comment by thescientist13** [comment]
Also noticing this bug, where if you go to a page and return, it's shelf items will not expand / collapse after an initial expand / collapse

#### Steps
1. Go to home page
1. Go to any page with expandable side nav items, like About (from header)
1. Go to Docs page (from header)
1. Go back to About page (from header)
1. Expand How It Works
1. Collapse How It Works
1. Expand How It Works

#### Expected
Use could keep expanding / collapsing

#### Actual
Section no longer expands / collapses

**Comment by hutchgrant** [comment]
I can't replicate this, are you missing a step here?

**Comment by thescientist13** [comment]
Created a video and posted to the Slack channel.  I think it's mainly around the carrot's themselves, for some reaosn.

**Comment by thescientist13** [comment]
Linking to https://github.com/ProjectEvergreen/greenwood/issues/112#issuecomment-622180442 since this is more related to CSS / UX, and not any bug per se.
