### ISSUE TITLE
better puppeteer support and stability

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#341]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently with our dependency on **puppeteer** requires [certain operating system dependencies](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md), this also means [consumers need to install some of these OS specific dependencies as well](https://github.com/ProjectEvergreen/greenwood/pull/335/files), which could become an issue, especially for beginners.

I know Angular's Scully uses puppeteer, wonder how they get around this?

## Details
I know Angular's [Scully](https://github.com/scullyio/scully) uses puppeteer, wonder how they get around this?

In addition, sometimes GitHub Actions and Netlify bomb out trying to run our builds, and not sure if they are related?
<img width="987" alt="netlify-deploy-failed" src="https://user-images.githubusercontent.com/895923/80649821-bfe1ae80-8a40-11ea-8156-997620ba004d.png">

#### GitHub Actions
https://github.com/ProjectEvergreen/greenwood/pull/314
```
1) Build Greenwood With: 
       Default Greenwood Configuration and Workspace w/Custom Style and Theme Page Template
         "before all" hook in "Default Greenwood Configuration and Workspace w/Custom Style and Theme Page Template":
     Error: the string "Error: Failed to launch chrome!\nUnable to revert mtime: /usr/share/fonts/cMap\nUnable to revert mtime: /usr/share/fonts/cmap/adobe-cns1\nUnable to revert mtime: /usr/share/fonts/cmap/adobe-gb1\nUnable to revert mtime: /usr/share/fonts/cmap/adobe-japan1\nUnable to revert mtime: /usr/share/fonts/cmap/adobe-japan2\nUnable to revert mtime: /usr/share/fonts/cmap/adobe-korea1\nInconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\n" was thrown, throw an Error :)
Edit - Delete
SUGGESTED
Feedback
ADD TO CARD
POWER-UPS
ACTIONS

```

#### Netlify
https://app.netlify.com/sites/elastic-blackwell-3aef44/deploys/5e96527d7900d90006e4c3c5
```
```

**Comment by hutchgrant** [comment]
The error you cited suggests an error with and/or missing fonts 

`adobe-japan1 adobe-japan2 and adobe-korea1  fonts`

I took a browse through [puppeteers troubleshooting documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) (note your link to troubleshooting docs has broken) and noticed it recommended installation of several fonts in the [puppeteer docker script](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)

```
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
```

Perhaps if we amend the chromium lib dependency install script with: 

```bash
apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends
```

It will fix the issue(which I haven't seen in a while).

**Comment by thescientist13** [comment]
Haven't had as many issues lately it seems, and #391 updates some of our guides around Puppeteer which is good, but I think there is still some documentation needed here, or if possible could we remove our dependency on the installer.sh script at all.  Maybe something possible in a new version of Puppeteer?

**Comment by hutchgrant** [comment]
None of us have seen this issue since and we've updated the dependency requirements in install.sh as per the maintainers recommendations. Not sure why this needs to stay open?

**Comment by thescientist13** [comment]
I tried to articulate that in the summary of the issue and in my comment, specifically around the OS specific dependencies ad the chromium installer script in general...
> Currently with our dependency on **puppeteer** requires [certain operating system dependencies](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md), this also means [consumers need to install some of these OS specific dependencies as well](https://github.com/ProjectEvergreen/greenwood/pull/335/files), which could become an issue, especially for beginners.

So I would still like to explore if there is a way around this completely.

**Comment by thescientist13** [comment]
Checked in on the [Scully](https://scully.io/) project (Angular's SSG tool) which pre-renders HTML as well and also uses [**puppeteer**](https://github.com/scullyio/scully/blob/main/libs/scully/package.json#L35), and they have a [disclaimer](https://scully.io/docs/learn/getting-started/requirements/) related to Chromium and OS related dependencies as well.  
> Chromium: **IMPORTANT**: Scully uses Chromium. Therefore, your Operating System, as well as its administrator rights must allow its installation and execution.

So at least now I can feel better knowing there's something we're not overlooking here.  🤞

Let me check in to see if there's any improvements on this process in later version's of puppeteer, since i know we're at least one major semver behind.

**Comment by thescientist13** [comment]
Even [**playwright**](https://playwright.dev/#version=v1.3.0&path=docs%2Fdocker%2FREADME.md&q=), also chromium based, enforces this same contingency.

**Comment by thescientist13** [comment]
I suppose this could probably be closed then, but maybe there are other thoughts how to serialize if we don't want to rely on a browser, but as we're supporting browser specific developer experiences, ShadowDOM, customElements, etc a browser may actually be the best way to be doing this.
