### ISSUE TITLE
Support custom webpack loader configurations

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#370]
## Type of Change
- [x] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently, if a user wants to add their own webpack plugins, they can do so [through the greenwood.config.js](https://www.greenwoodjs.io/plugins/webpack).  But what if a user wants to modify an existing loader?  I propose allowing user overrides of webpack loaders.  ~~production, development, and common configs. As well as an ability to eject current configs to user's workspace(maybe a separate issue/PR).~~

## Details

Users need to be able to modify webpack configurations for a variety of things.  For example, if I want to add rehype plugins to wc-markdown-loader, I would need access to the webpack config so that I can add:

```js
{
        test: /\.md$/,
        loader: 'wc-markdown-loader',
        options: {
          defaultStyle: false,
          shadowRoot: false,
          preset: {
            settings: { commonmark: true, bullet: '*', emphasis: '*', fences: true },
            plugins: [
              require('rehype-slug'),
              require('rehype-autolink-headings')
            ]
          }
        }
      }, 
```

My Suggestion for accomplishing this is:
- ~~modify context lifecycle to check for if a webpack config exists~~
- ~~modify build/develop tasks to use the compilation.context to decide what webpack config to use~~
- add support for custom webpack loaders (as experimental) as we have support [custom **webpack** plugins](https://www.greenwoodjs.io/plugins/).

A future idea would be to have a CLI command to eject the configs into the user's project directory.

**Comment by thescientist13** [comment]
I think this might in theory solve #46 ?
