### ISSUE TITLE
As a developer, I would find a video series embedded in documentation pages to be useful.

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#380]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

In addition to our guides, getting-started, and documentation, I propose a series of youtube videos for each step of development.  These videos can be embedded either within the docs/guides or their own seperate page.  Videos can either be just simple user-generated ones or branded greenwood with logo, intro, music, and citations to social media(twitter/github).

## Details

1. Project Setup - Install dependency, scaffold and organize a basic project. no content yet just get default greenwood index page to display
2. Create Content - Do basic page creation overview with small bits of information on front-matter
3. Web Components and Styling - basic component creation, import and styling
4. Create and use a custom page Template
5. Create and use a custom app Template
6. Deployment to github and then netlify
7. Various alternative deployment methods
8. Writing a greenwood plugin
9. Contributing to greenwood

**Comment by thescientist13** [comment]
Moving a discussion - https://github.com/ProjectEvergreen/greenwood/discussions/850
