### ISSUE TITLE
lazy loaded routes have no loading component in SPA

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#384]
## Type of Change
- [x] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

When we lazy load routes in SPA, we have no placeholder component between route changes. This causes as an ugly bug on greenwood's current site where the content disappears, while the header and footer get smashed together. In the initial PR there was a loading circle that was distracting so we removed it. But we never filled that placeholder with something else.  Furthermore, all developer apps will also wish to use this feature(which [lit-redux-router merged](https://github.com/fernandopasik/lit-redux-router/pull/14)). 

## Details

I suggest an overrideable default loading component. It can be overridden the same way page templates are overridden.  It must have the same filename and use the same component element definition. e.g. `<eve-loading></eve-loading>`

**Comment by thescientist13** [comment]
We don't manage the SPA architecture anymore as of #856 and so all this application stuff is now entirely controllable from userland, so nothing needed from us now!  👍
