### ISSUE TITLE
nested pages are not returned in order as they are on the filesystem

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#386]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Getting intermittent test failure similar to the issue observed in #271 , in that the order of pages returned did not seem to returned from the graph in the same order as they are on the filesystem, in particular when there are multiple files in nested directories.  I notice our test case does not act and trying to do a map in the template, e.g.

While it is always true that users can do their filtering and sorting client side, Greenwood should at least to a consistent, default, predictable return order.

## Details
For example, when working on [the PR](https://github.com/ProjectEvergreen/greenwood/pull/383) for #371 I created a directory structure for the graph test case, [similar to my website](https://github.com/thegreenhouseio/www.thegreenhouse.io/tree/master/src/pages/blog) in that it had nested directories like below
```shell
src/
  index.md
  pages/
    blog/
      first-post.md
      second-post.md
    index.md
```

And in a template, listing the posts on the page
```js
class BlogTemplate extends LitElement {
  ...

  async connectedCallback() {
    super.connectedCallback();
    const response = await client.query({
      query: ChildrenQuery,
      variables: {
        parent: 'blog'
      }
    });

    this.posts = response.data.children.filter(post => {
      return post.filePath.indexOf('/blog/index') < 0;
    });
  }

  /* eslint-disable indent */
  render() {
    const { posts } = this;

    return html`

      <div class='container'>
          <ul>
            ${posts.map((post) => {
              return html`
                <li>
                  <a href="${post.link}" title="Click to read my ${post.title} blog post">${post.title}</a>
                </li>
              `;
            })}
          </ul>
      </div>
    `;
  }
  /* eslint-enable */
}

customElements.define('page-template', BlogTemplate);
```

However, intermittently, i would get this error
```shell
551 passing (5m)
  4 failing

  1) Build Greenwood With:
       Data from GraphQL
         Home (Page Template) w/ Navigation Query
           should have a expected NavigationQuery output in the <header> tag:

      AssertionError: expected '/blog/second-post/' to equal '/blog/first-post/'
      + expected - actual

      -/blog/second-post/
      +/blog/first-post/

      at Context.<anonymous> (packages/cli/test/cases/build.data.graph/build.data.graph.spec.js:114:57)

  2) Build Greenwood With:
       Data from GraphQL
         Blog Page (Template) w/ Navigation and Children Query
           should have expected navigation links in the <header> tag tag when using NavigationQuery:

      AssertionError: expected '/blog/second-post/' to equal '/blog/first-post/'
      + expected - actual

      -/blog/second-post/
      +/blog/first-post/

      at Context.<anonymous> (packages/cli/test/cases/build.data.graph/build.data.graph.spec.js:156:57)

  3) Build Greenwood With:
       Data from GraphQL
         Blog Page (Template) w/ Navigation and Children Query
           should have expected blog posts links in the <body> tag when using ChildrenQuery:

      AssertionError: expected '/blog/second-post/' to equal '/blog/first-post/'
      + expected - actual

      -/blog/second-post/
      +/blog/first-post/

      at Context.<anonymous> (packages/cli/test/cases/build.data.graph/build.data.graph.spec.js:175:57)

  4) Build Greenwood With:
       Data from GraphQL
         Blog Post Pages (Post Template) w/ custom Graph Query
           should have expected navigation links in the <header> tag tag when using NavigationQuery:

      AssertionError: expected '/blog/second-post/' to equal '/blog/first-post/'
      + expected - actual

      -/blog/second-post/
      +/blog/first-post/

      at Context.<anonymous> (packages/cli/test/cases/build.data.graph/build.data.graph.spec.js:219:56)
```

----

Interestingly, there is a nested test case, but it doesn't have multiple files in the nested directory, like described above.  I would start by updating that test case to something like
```shell
src/
  index.md
  pages/
    blog/
       2019/
        first-post.md
        second-post.md
      2020/
        first-post.md
        second-post.md
        third-post.md
    index.md
```

And return in the following order
1. _/blog/2019/first-post.md/
1. _/blog/2019/second-post.md/
1. _/blog/2020/first-post.md/
1. _/blog/2020/second-post.md/
1. _/blog/2020/third-post.md/
1. _/blog/index.md/

**Comment by thescientist13** [comment]
So I ran the PR at [commit `385eeeb`](https://github.com/ProjectEvergreen/greenwood/pull/383/commits/385eeebe0faefe216a1f212563cc0dbcf50d52d8) five time in GitHub actions (thought it doesn't display 5 runs) and also ran it five times locally and was not able to replicate it.  Maybe just had a local change that threw of the test that I fixed and didn't realize it?

**Comment by hutchgrant** [comment]
I too was unable to replicate this bug on a fresh project with the same suggested file structure. Can't test a fix if can't replicate. Test it on a slower machine, with larger pages, run it more times until you break it? I don't know.

**Comment by thescientist13** [comment]
Could have just made a change or forgot to save a file.  Was at the tail end of a bunch of work so who knows.  Glad to hear it's working for you too.  🍀

**Comment by thescientist13** [comment]
Not one failing build in this PR even with a bunch more branch runs, so going to consider this cannot reproduce.

**Comment by thescientist13** [comment]
Sad to say, but it looks like this issue may still be relevant :/
https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/174#issuecomment-744641842
