### ISSUE TITLE
missing gwd prefix in style affecting page minimum height

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#394]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarixy below)

## Summary
As noted in #384 the page currently jumps when content disappears due to the content wrapper not having a minimum height.  The style is already present in app-template but we forgot to rename it when we added gwd prefixes in #378

## Details
* Fix remaining missing style prefix in app template

**Comment by thescientist13** [comment]
[already fixed](https://github.com/ProjectEvergreen/greenwood/pull/395#issuecomment-662201844)
