### ISSUE TITLE
assets are being fetched twice from different hosts

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#404]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Images are being fetched twice, once from _assets/*_ and another call from CloudFront (Netlify).
<img width="842" alt="Screen Shot 2020-07-28 at 8 10 43 PM" src="https://user-images.githubusercontent.com/895923/88742820-2b571d00-d111-11ea-82f6-0682bf3aeb1a.png">

## Details
Could just be a Netlify setting?
![netlify-optimization](https://user-images.githubusercontent.com/895923/88742731-e9c67200-d110-11ea-983b-1acecc181d62.png)

But ideally, we would want these images served from a CDN though... wonder if we can get the best of both worlds?  🤔

**Comment by thescientist13** [comment]
Seems to be happening with fonts too as part of https://github.com/ProjectEvergreen/greenwood/pull/402, which loads fonts from _/assets/_
<img width="839" alt="Screen Shot 2020-07-28 at 8 10 56 PM" src="https://user-images.githubusercontent.com/895923/88743745-740fd580-d113-11ea-81e0-43b0200c836a.png">

**Comment by thescientist13** [comment]
@hutchgrant / @aholtzman 
I was just checking in on this, but it looks like it's only happening for me in branch preview environments.  If I'm reviewing [a PR](https://github.com/ProjectEvergreen/greenwood/pull/402), I will see the request from both _assets/_ and CloudFront.

But on production website, the font only loads from CloudFront?  Not sure if either of you can confirm.

----

On a related note, I wonder if we should benchmark with and without Netlify asset optimization?  I wonder if it would be better to make sure Greenwood is doing that all on its own, so it either doens't conflict with what Netlify is trying to do, or unintentionally gets a boost that makes it seem to only work better on Netlify.  (e.g. false positive).

Thoughts?

**Comment by hutchgrant** [comment]
I'd like to see the difference with an without optimization.  Why don't you turn it off and recompile site and test both(I don't have access to greenwood's netlify).  I know, testing production is bad. For 5 minutes, it shouldn't be that big a deal.

**Comment by thescientist13** [comment]
OK, disabled this all completely in prod and [rebuilt and cleared the site cache via Netlify](https://app.netlify.com/sites/elastic-blackwell-3aef44/deploys/5f26e226dc0ccb5c7332c2b2) and things are looking much better!
<img width="1670" alt="Screen Shot 2020-08-02 at 12 01 37 PM" src="https://user-images.githubusercontent.com/895923/89126981-0dded600-d4b8-11ea-9ac1-a9ce75e51e7d.png">

<img width="1675" alt="Screen Shot 2020-08-02 at 12 01 46 PM" src="https://user-images.githubusercontent.com/895923/89126987-120af380-d4b8-11ea-948d-9846b65cdbf5.png">


Found [this thread](https://community.netlify.com/t/asset-optimization-preloading-fonts/3197/7) where others reported similar issues but I'm pretty sure Netlify already serves everything off of a CDN anyway so losing the CloudFront specific routes shouldn't be a big deal anyway, and our score definitely didn't get harmed, so I say this is a winner.

I think I'll add a _netlify.toml_ for this and other settings, so we can track stuff like this and #331 via code.

**Comment by thescientist13** [comment]
We should definitely look into font / image preloading though, I think that would be super helpful to have a solution / best practice for.

**Comment by hutchgrant** [comment]
can we close this issue then.  Loading seems smoother.

**Comment by thescientist13** [comment]
Shortly, will make some notes in our guides and introduce a _netlify.toml_.  Doing that now.
