### ISSUE TITLE
Switch website to use Netlify Analytics instead of Google Analytics

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#405]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
It would be nice to have to understand what is required if anything to setup [Netlify Analytics](https://www.netlify.com/products/analytics/), in favor of using our [Google Analytics plugin](https://github.com/ProjectEvergreen/greenwood/tree/master/packages/plugin-google-analytics).

## Details
It seems like there is zero setup, so sounds like just a question of turning it on?  (and then disabling Google Analytics from our site).

Maybe even worth commenting as such in the Google Analytics plugin, as a suggestion to those already using Netlify?

**Comment by thescientist13** [comment]
@aholtzman 
Not sure if this is something you might be interested into looking into?

**Comment by aholtzman** [comment]
There is no setup for Netlify Analytics, you just have to have a credit card on file for the monthly fee. Both Netlify & Google Analytics can be run simultaneously if one wanted to do a comparison of the two. 

There are differences between them and it would be good to point to any articles contrasting the two for an informed choice. Maybe add a line to the Google Analytics doc that says "If you are deploying your project with Netlify, they have a no configuration paid analytics service that does not impact your sites performance you may want to consider. More information comparing the tow services can be found here (link to relevant article)"

**Comment by aholtzman** [comment]
I did a quick scan of this, it looks like a fair assessment of the two [https://blog.jim-nielsen.com/2020/google-vs-netlify-analytics/](https://blog.jim-nielsen.com/2020/google-vs-netlify-analytics/)

**Comment by thescientist13** [comment]
Great article @aholtzman, and I know personally, I pretty much relate to this part the most
> I’ve never really used the analytics for anything other than satisfying my own personal curiosity. 

The points around no JavaScript needed, all server side, and cool utilities like "Resources Not Found" are pretty compelling so I think we should definitely open a PR adding the language about using Netlify Analytics if using Netlify to the README of the Google Analytics Plugin.

That said, $10/month ain't peanuts though.  I'll think about if we want / need to enable it for this site then (and remove GA).  Or just disable all Analytics completely?
