### ISSUE TITLE
assemble page and app <head> tags in the correct order 

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#431]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently when a page is assembled into an app template in HTML transformation, script / style / link tags from the page are not appended _after_ all the app ones, instead they are appended after just the _first one_

currently its like this
```html
<head>
   <script app-1>
   <script page-1>
   <script page-2>
   <script app-2>
</head>
```

it should be like this
```html
<head>
   <script app-1>
   <script app-2>
   <script page-1>
   <script page-2>
</head>
```

## Details
Basically this code is too naive with the regex, maybe it would be better to use HtmlParser like in rollup?
```js
headScripts.forEach(script => {
  if (script.rawAttrs !== '') {
    appTemplateContents = appTemplateContents.replace(/<\/script>/, `
      </script>\n
      <script ${script.rawAttrs}></script>\n
    `);
  }

  if (script.rawAttrs === '') {
    appTemplateContents = appTemplateContents.replace(/<\/script>/, `
      </script>\n
      <script>
        ${script.text}
      </script>\n
    `);
  }
});

headLinks.forEach(link => {
  appTemplateContents = appTemplateContents.replace(/<\/link>/, `
    </link>\n
    <link ${link.rawAttrs}></link>\n
  `);
});
```

In general, this naive regexing throughout may want to be refactored.  But that could be another ticket.  Not sure which is faster (regex vs parser?

**Comment by hutchgrant** [comment]
My preference is to do this with jsdom. Also the problem is we're adding the page scripts at the same time as filling the page-outlet, this becomes problematic with ordering when you also have to fill the meta, importmap, and livereload.

**Comment by thescientist13** [comment]
What I had in mind for this (and anywhere we are doing for this kind of find / replace / regex) was doing more things like this from the [_rollup.config.js_](https://github.com/ProjectEvergreen/greenwood/blob/rfc/issue-355-no-bundle-development/packages/cli/src/config/rollup.config.js#L47) to programmatically walkthrough markup strings.
```js
const parser = new htmlparser2.Parser({
  onopentag(name, attribs) {
    if (name === 'script' && attribs.type === 'module' && attribs.src) {
      const srcPath = attribs.src.replace('../', './');
      const scriptSrc = fs.readFileSync(path.join(userWorkspace, srcPath), 'utf-8');

      that.emitFile({
        type: 'chunk',
        id: srcPath,
        name: srcPath.split('/')[srcPath.split('/').length - 1].replace('.js', ''),
        source: scriptSrc
     });

      // console.debug('emitFile for script => ', srcPath);
   }
 }
});
```

I don't think we require an entire browser implementation just for this. Plus, can JSDOM even do that?  I thought it was more for emulating a browser environment in JS.

Even with some generous marge, [**JSDOM**](https://bundlephobia.com/result?p=jsdom@16.4.0) is MBs say compared to something like [**htmlparser2**](https://bundlephobia.com/result?p=htmlparser2@5.0.1) so that's a lot of overhead / potential overkill.

**Comment by hutchgrant** [comment]
well this isnt running on the browser, 2mb on the compiling machine is nothing. Especially when you consider puppeteer also downloads chromium(~170MB Mac, ~282MB Linux, ~280MB Win).  Mine was a hacky solution, similar to the replace but a little better imo. That said, if we can do it with rollup that would be nice too. I dont have experience with it.

**Comment by thescientist13** [comment]
Fair point, but unfortunately there's no other way to render web components without a browser, so puppeteer is kind of our only option there.  But say for local development where serialization doesn't occur, JSDOM seems like a lot of overhead for effectively what we want, which is just a more ergonomic alternative to a `string.replace(/* */)` * all the instances we may need to invoke it.  

Being able to quickly assemble bits of HTML on the fly might not be JSDOM's strong suit is all, and so I guess in my mind if all the problem calls for is just a tool for concatenating some string together in a programmatic way, a parser seems a little more specialized for the task.  Certainly open to seeing alternatives in action, just that JSDOM seemed a bit heavy handed when just exploring the idea off the top of my head.  (and we did already [remove it from our flow once before](https://github.com/ProjectEvergreen/greenwood/pull/192), so I think there's a case to keep it out of our flow unless absolutely necessary).
