### ISSUE TITLE
add support for configuring lang attribute in default template

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#558]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
As part of the PR for #512, the question came up regarding default [app templates](https://github.com/ProjectEvergreen/greenwood/blob/release/0.10.0/packages/cli/src/templates/app.html) and what the default HTML tags should, and in particular the [`lang` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang).
```html
<html lang="en" prefix="og:http://ogp.me/ns#">
```

It is a required attribute, but it's also meant to be contextual to the language content of the project.

## Details
My first thought would be that user's could provide a lang config property, and that we could swap out that part for them.

```js
// greenwood.config.js
module.exports = {
  lang: "xx"
}
```

Then we would return the default template with their lang
```html
<html lang="xx" prefix="og:http://ogp.me/ns#">
```

---

Open to other options, but I think it would be important to make this easy, but not also not sure how often someone would want to configure lang _but not_ also be using their own app template?  🤔

**Comment by mknee40** [comment]
Wouldn't just manually changing the lang attribute have the same effort as adding it in the configuration file? Im not sure how many templates you would be using, but even if you had 10 templates, this is still not going to take long to update. 
Does the language configuration affect anything other than the value in the html template, for example, any translation components?

**Comment by thescientist13** [comment]
Yeah, that's definitely a good point regarding just writing it all in HTML as opposed to wrapping it up all in JavaScript somewhere.  For example, the same could be said of being able to pass `<meta>` tags programmatically (an earlier design decision) where as to your point, it would probably be just as easy now (arguably easier) to just write the plain HTML right in your own code.  

It's definitely a question I have had in the back of my mind.

Plus, this would only account for our [default _app-template.html_](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/templates/app.html) anyway so, it's a good question to say: _how much work should be put into a potentially minimally used feature?  (potentially)_. 🤔

**Comment by thescientist13** [comment]
Not sure if this is worth it, along the lines of #851 ?  Probably just recommend users set it themselves, or if it does need to be configurable, then that use case is likely in the scope of i18n which is a much larger conversation to be had.
