### ISSUE TITLE
[RFC] Move page template scaffold to webpack wc-markdown-loader

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#61]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

This is a proposal(WIP), I do not have a working version, this is purely theory. I want to discuss the pros and cons and whether it's worth pursuing this idea because it will come with problems and benefits. It likely cannot be done in a single PR. We can try, but I imagine it will have consequences later that will have to be smoothed out.

### Currently

.md files are loaded via wc-markdown-loader, [they're built into web components and exported](https://github.com/hutchgrant/wc-markdown-loader/blob/master/src/build.js#L34-L51) e.g. `<wc-md-hello></wc-md-hello>`. 

A page template selected for each .md file(page-template.js by default)  is then used to scaffold a new web component that contains that .md file exported component within `scaffold.js`. The newly scaffolded component is put in scratch directory and imported to app.js

### Suggested changes

Remove `writePageComponentFromTemplate()` from `scaffold.js` and place it instead in the wc-markdown-loader.  Using the graph, load the required template from within the loader and [build using the template here](https://github.com/hutchgrant/wc-markdown-loader/blob/master/src/build.js#L34-L51).

We will then have to change the imports file `list.js` to use markdown files and not the scaffolded .js files within scratch directory.

### Pros

assuming we can adjust import path context:
* make global css much easier
* make meta much easier
* make page template styling easier(no additional shadow dom, no need to import duplicate css and render it within each individual md file as we currently are in mock-app)
* may make live-reload in develop easier
* may be more modular, more reliant on webpack loaders, making it easier to modularize for plugins  etc in the future

### Cons

* we may not be able to adjust import path so that it's relative to user workspace
* may encounter issues with `list.js` using markdown from the user workspace instead of js from scratch directory
* may encounter issues with the current context replacement, which was tricky to setup

I'll update pros and cons on the list if you have any ideas or criticism here.  It may not be worth the effort to do.

**Comment by thescientist13** [comment]
As part of #355 / #417 webpack wont be used in the project anymore, so this issue will become invalid once this gets merged and release.

**Comment by thescientist13** [comment]
v0.10.0 released, webpack related issues no longer apply to the project
