### ISSUE TITLE
Wrongly documented installation instructions

### ISSUE THREAD

**Issue by almondtools** [ProjectEvergreen/greenwood#704]
## Type of Change
- [X ] Documentation / Website

## Summary
npm usage is wrong

## Details

`npm -i @greenwood/cli --save-dev` does not work, `npm i @greenwood/cli --save-dev` or `npm install @greenwood/cli --save-dev` does.

**Comment by thescientist13** [comment]
Thanks again for reporting @almondtools , should be all fixed up now in our docs and on npm!  👍
