### ISSUE TITLE
clean up unnecessary scrollbars on the website

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#734]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Not sure if its something new to our code, but it seems like we've acrrued some extra scrollbars now??

#### Home Page
Horizontal scrollbar
https://www.greenwoodjs.io
![Screen Shot 2021-09-21 at 12 48 21 PM](https://user-images.githubusercontent.com/895923/134213951-542bfd9b-ca75-467c-89e9-e68923b3d7d0.png)

#### Docs / Guides / etc pages
Double vertical scrollbars
https://www.greenwoodjs.io/docs
https://www.greenwoodjs.io/guides
![Screen Shot 2021-09-21 at 12 50 04 PM](https://user-images.githubusercontent.com/895923/134213906-9eb1d769-e657-4143-b69c-2c61eec25c6a.png)
![Screen Shot 2021-09-21 at 12 53 46 PM](https://user-images.githubusercontent.com/895923/134214000-13b7b524-8cc3-4e9f-901d-44ba4c0602d1.png)

**Comment by theprojectcode** [comment]
Is this issue still open? I would like to contribute.

**Comment by thescientist13** [comment]
Hey @theprojectcode , thanks for checking in on this one!

While it looks like there is already a PR open for this, I think these other two issues would be really helpful to us, if you're interested?
- #718 
- #643

If they do (or you're looking for other types of contribution areas) feel free to let us know, we do appreciate the interest and help.  😊

**Comment by theprojectcode** [comment]
@thescientist13 can I contribute to ticket #643? I'd be happy to do that one.

**Comment by thescientist13** [comment]
Definitely @theprojectcode !  I've assigned it to you, and feel free to reach out in that particular if you have any questions.  (or you can join us in our Slack too)

**Comment by theprojectcode** [comment]
Awesome! @thescientist13 I'll work on it!
