### ISSUE TITLE
quick start page iframe (stackblitz) is scroll jacking the page

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#797]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
If you go to the [Quick Start](http://localhost:1984/getting-started/quick-start/) page which hosts the Stackblitz iframe, the page, upon load, will automatically scroll to the position of the iframe.  Can reproduce on Chrome and FF. (on Mac).

https://user-images.githubusercontent.com/895923/140791644-23ecde4c-9d14-4ee0-936f-8785bdf896a5.mov

## Details
This is less than desirable since the iframe is heavy and ideally should only be lazy loaded and when on desktop breakpoints.  I think when the [media query kicks in sets it to `display: block` is what is causing it](https://github.com/ProjectEvergreen/greenwood/blob/master/www/styles/page.css#L141)? It definitely seems browser related since the URL is not changing at all. 🤔 
- https://community.atlassian.com/t5/Questions-for-Confluence/Prevent-Firefox-to-auto-scroll-to-an-HTML-embedded-iframe/qaq-p/1215591
- https://community.atlassian.com/t5/Confluence-questions/Prevent-a-page-from-scrolling-to-an-iframe/qaq-p/1726846

cc: @aholtzman  🙏

**Comment by aholtzman** [comment]
I have not seen this behavior before. Removing the media query and `display` does not change this glitch. There really should be a way to solve this without a JS hack, I just do not know what it is at the time - besides using Safari.

**Comment by thescientist13** [comment]
Actually, looks like it may have been a Stackblitz issue - https://github.com/stackblitz/core/issues/1653.

Let me know if you can reproduce, as it seems to be fixed for me now, and if so, we can close.  🙌

**Comment by aholtzman** [comment]
I looks like it is acting normally in Chrome for me now.

**Comment by thescientist13** [comment]
awesome sauce.
