### ISSUE TITLE
greenwood website page style is displaying scroll bars

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#830]
## Type of Change
- [ ] New Feature Request
- [x] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
The greenwood site is displaying scroll bars next to the content.

![image](https://user-images.githubusercontent.com/1429612/146838268-5ffa65c4-80d7-45a5-a2ed-8345f68c96d8.png)

## Details

The page style needs to have `overflow: scroll` removed

**Comment by thescientist13** [comment]
Interesting.  What browser / OS are you using?  not seeing it on Chome 96 / macOS.

**Comment by hutchgrant** [comment]
chrome Version 96.0.4664.110 (Official Build) (64-bit). 
Not zoomed in at all. Even zooming and unzooming i'm still seeing it.
1920x1080

**Comment by hutchgrant** [comment]
Can also see it on firefox 95, though its faded

![image](https://user-images.githubusercontent.com/1429612/146839374-32fc29c2-0b41-4545-b6f8-d4be14c5bd73.png)
